package AerodromData;


import AerodromData.direktorPanel;
import AerodromData.menadzerPanel;
import AerodromData.radnikPanel;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Login_panel extends javax.swing.JFrame {

    /**
     * Creates new form Login_panel
     */
    public Login_panel() {
        initComponents();
        setTitle("Prijava Zaposlenih");
        setLocationRelativeTo(null);
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jbPrijava = new javax.swing.JButton();
        jtxtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Korisničko ime:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Lozinka: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        getContentPane().add(jtxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 144, -1));

        jbPrijava.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jbPrijava.setText("Prijava");
        jbPrijava.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPrijava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPrijavaMouseClicked(evt);
            }
        });
        jbPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrijavaActionPerformed(evt);
            }
        });
        getContentPane().add(jbPrijava, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 90, -1));

        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 144, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AerodromData/Webp.net-resizeimage.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordActionPerformed

    private void jbPrijavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPrijavaMouseClicked

    }//GEN-LAST:event_jbPrijavaMouseClicked

    private void jbPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrijavaActionPerformed
        try {
            int TipKorisnika=10;
            Connection conn= DriverManager.getConnection("jdbc:derby://localhost:1527/AerodromDB","quantumair","quantumair");
            Statement st= conn.createStatement();
            ResultSet rs = st.executeQuery("select * from ZAPOSLENI");
            while(rs.next())
            {
                if(rs.getString(5).equals(jtxtUserName.getText()) && rs.getString(6).equals(jtxtPassword.getText()))
                {
                TipKorisnika=rs.getInt(7);
                break;
                }
                else{
                TipKorisnika=0;
                }
            }
            if(TipKorisnika == 0)
            {
            Greska prikaziGresku=new Greska();
prikaziGresku.setVisible(true);  
            }
            else if(TipKorisnika==1)
                    {
                        radnikPanel radnikovpanel=new radnikPanel();
radnikovpanel.setVisible(true);
        this.dispose();
                    }
            else if(TipKorisnika==2)
                    {
                       menadzerPanel menadzerovpanel=new menadzerPanel();
menadzerovpanel.setVisible(true);
        this.dispose(); 
                    }
            else if(TipKorisnika==3)
                    {
                       direktorPanel disinpanel=new direktorPanel();
disinpanel.setVisible(true);
        this.dispose(); 
                    }
        } catch (SQLException ex) {
            Logger.getLogger(Login_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbPrijavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbPrijava;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUserName;
    // End of variables declaration//GEN-END:variables

    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
